// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareTestBatches(arg1) {
  return window['go']['main']['App']['CompareTestBatches'](arg1);
}

export function ExportTestData(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportTestData'](arg1, arg2, arg3);
}

export function GetAllTestBatches() {
  return window['go']['main']['App']['GetAllTestBatches']();
}

export function GetAvailableModels(arg1, arg2) {
  return window['go']['main']['App']['GetAvailableModels'](arg1, arg2);
}

export function GetDefaultPromptLengths() {
  return window['go']['main']['App']['GetDefaultPromptLengths']();
}

export function GetDefaultTestConfiguration() {
  return window['go']['main']['App']['GetDefaultTestConfiguration']();
}

export function GetExportDirectory() {
  return window['go']['main']['App']['GetExportDirectory']();
}

export function GetPromptTypes() {
  return window['go']['main']['App']['GetPromptTypes']();
}

export function GetTelemetryUpdates() {
  return window['go']['main']['App']['GetTelemetryUpdates']();
}

export function GetTestBatch(arg1) {
  return window['go']['main']['App']['GetTestBatch'](arg1);
}

export function GetTestProgress() {
  return window['go']['main']['App']['GetTestProgress']();
}

export function GetTestResults() {
  return window['go']['main']['App']['GetTestResults']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function StartSpeedTest(arg1) {
  return window['go']['main']['App']['StartSpeedTest'](arg1);
}

export function StopSpeedTest(arg1) {
  return window['go']['main']['App']['StopSpeedTest'](arg1);
}

export function ValidateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ValidateAPIKey'](arg1, arg2);
}

export function ValidatePromptConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidatePromptConfig'](arg1, arg2);
}
