// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompareTestBatches(arg1:Array<string>):Promise<main.ComparisonResult>;

export function ExportTestData(arg1:string,arg2:string,arg3:main.ExportOptions):Promise<string>;

export function GetAllTestBatches():Promise<Array<main.TestBatch>>;

export function GetAvailableModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetDefaultPromptLengths():Promise<Array<number>>;

export function GetDefaultTestConfiguration():Promise<main.TestConfiguration>;

export function GetExportDirectory():Promise<string>;

export function GetPromptTypes():Promise<Array<string>>;

export function GetTestBatch(arg1:string):Promise<main.TestBatch>;

export function GetTestProgress():Promise<Array<main.ProgressUpdate>>;

export function GetTestResults():Promise<Array<main.TestResult>>;

export function Shutdown():Promise<void>;

export function StartSpeedTest(arg1:main.TestConfiguration):Promise<main.TestBatch>;

export function StopSpeedTest(arg1:string):Promise<void>;

export function ValidateAPIKey(arg1:string,arg2:string):Promise<void>;

export function ValidatePromptConfig(arg1:string,arg2:number):Promise<void>;
